# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || 首页
  #galleries: /galleries || 摄影
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Color
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Font
font:
  size: 14px
  family: 

# Background Image
background_image:

# Loading
loading: /images/theme/loading.gif

# Preview
preview:
  enable: true
  model: wave  # wave cloud
  background:
    default: https://cdn.jsdelivr.net/gh/kangshitao/BlogPicture@main/img/welcome-image.jpg
    api: # https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: 心之所向，素履以往
    color: '#ffffff'
    api: https://v2.jinrishici.com/one.json
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=1574716653 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  #instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/kangshitao || icongithub-fill || '#24292E'
  email: mailto:1574716653@qq.com || iconmail

# Override Scrollbar
scrollbar:
  model: simple # default simple normal none

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# QR Code
qrcode:
  enable: true
  type: url # url image
  image: #https://pic.izhaoo.com/weapp-code.jpg

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Post Image
post_image:
  random: local # local galleries
  default: /images/theme/post_image/5.jpg

# Page Size
post_page_size:
  width: 1000px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate
donate:
  enable: true
  alipay: https://cdn.jsdelivr.net/gh/kangshitao/BlogPicture@main/img/alipay.jpg
  wechat: https://cdn.jsdelivr.net/gh/kangshitao/BlogPicture@main/img/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # html markdown text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: true
  type: valine
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId: C1IH3DfcmYPQ1T2Ox2nh15Xt-gzGzoHsz
  appKey: tRi9LbD7i7Gdlj8fYrUXJK6S
  placeholder: write comment content... 
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao https://txc.qq.com/
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: true
  appId: dVB32zRRBIgKa5WuB56mtboj-gzGzoHsz
  appKey: XipU873t8gkSypbwl1HWUARD
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading: /images/theme/loading.gif
  
# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Monokai Sublime  #Atelier Heath Light  # 浅色模式的代码风格
    dark: Dracula # 深色模式下的代码风格

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: # id
  google: G-0FZTGJZNYS # id
  tencent: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://cdn.bootcdn.net/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: //at.alicdn.com/t/font_1445822_s6x2xcokxrl.css

# Custom
custom:
  head:
  foot:
  css:
  js:
